"use client";
import "bootstrap/dist/css/bootstrap.min.css";
import { useEffect } from "react";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	useEffect(() => {
		require("bootstrap/dist/js/bootstrap.bundle.min.js");
	}, []);
	return (
		<html lang="en">
			<body className="body">
				<Navbar />
				<div className="mt-5 pt-4">{children}</div>

				<div className="mt-5 pt-4">
					<Footer />
				</div>
			</body>
		</html>
	);
}
